index:
    path: /
    controller: App\Controller\DefaultController::index
portfolio:
    path: /portfolio
    controller: App\Controller\DefaultController::showPortfolio
portfolioCategory:
    path: /portfolio/{slug}
    controller: App\Controller\DefaultController::showPortfolioCategory
admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::showAdminPanel
editCategory:
    path: /edit/category/{slug}
    controller: App\Controller\Admin\AdminController::editCategory
deleteCategory:
    path: /delete/category/{slug}
    controller: App\Controller\Admin\AdminController::deleteCategory
is_posted:
    path: /admin/is_posted
    controller: App\Controller\Admin\AdminController::setIsPosted
editPhotoshoot:
    path: /admin/edit/{id}
    controller: App\Controller\Admin\AdminController::editPhotoshoot
deletePhotoshoot:
    path: /admin/delete/{id}
    controller: App\Controller\Admin\AdminController::deletePhotoshoot
addPhotoshoot:
    path: /admin/addPhotoshoot
    controller: App\Controller\Admin\AdminController::addPhotoshoot
editPhotoshootImages:
    path: /admin/editImages/{id}
    controller: App\Controller\Admin\AdminController::editPhotoshootImages
deleteImage:
    path: /admin/deleteImage/{id}
    controller: App\Controller\Admin\AdminController::deleteImage
addCategory:
    path: /admin/addCategory
    controller: App\Controller\Admin\AdminController::addCategory
adminPortfolioCategory:
    path: /admin/category/{slug}
    controller: App\Controller\Admin\AdminController::adminPortfolioCategory
editIndexInfo:
    path: /admin/editIndex
    controller: App\Controller\Admin\AdminController::editIndexInfo